[package]
name = "schema"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
domain = { path = "../domain" }
infra = { path = "../infra" }
serde.workspace = true
utoipa.workspace = true

[dev-dependencies]
serde_json.workspace = true
