export const ROUTE_NAMES = {
  LOGIN: "Login",
  SETUP: "Setup",
  PROJECTS: "Projects",
  PROJECT_OVERVIEW: "ProjectOverview",
  CONFIG_FILE_LIST: "ConfigFileList",
  PROJECT_ENVIRONMENT_LIST: "ProjectEnvironmentList",
  DEPLOYMENT_LIST: "DeploymentList",
  DEPLOYMENT_DETAIL: "DeploymentDetail",
  DEPLOYMENT_PREVIEW: "DeploymentPreview",
  DRAFT_EDITOR: "DraftEditor",
  RELEASE_LIST: "ReleaseList",
  RELEASE_DETAIL: "ReleaseDetail",
  RELEASE_DIFF: "ReleaseDiff",
  PROJECT_MEMBERS: "ProjectMembers",
  SYNC_RECORD_LIST: "SyncRecordList",
  HEARTBEAT_LIST: "HeartbeatList",
  AUDIT_LOG_LIST: "AuditLogList",
  // Platform admin routes
  ADMIN_DASHBOARD: "AdminDashboard",
  ADMIN_USERS: "AdminUsers",
  ADMIN_PROJECTS: "AdminProjects",
  ADMIN_CREATE_PROJECT: "AdminCreateProject",
} as const;

export const ROUTE_PATHS = {
  LOGIN: "/login",
  SETUP: "/setup",
  PROJECTS: "/projects",
  PROJECT: "/projects/:projectId",
  CONFIG_FILE_LIST: "/projects/:projectId/config-files",
  PROJECT_ENVIRONMENT_LIST: "/projects/:projectId/environments",
  DEPLOYMENT_LIST: "/projects/:projectId/deployments",
  DEPLOYMENT_DETAIL: "/projects/:projectId/deployments/:deploymentId",
  DEPLOYMENT_PREVIEW: "/projects/:projectId/deployments/:deploymentId/preview",
  DRAFT_EDITOR:
    "/projects/:projectId/deployments/:deploymentId/configs/:configFileId/draft",
  RELEASE_LIST: "/projects/:projectId/releases",
  RELEASE_DETAIL: "/projects/:projectId/releases/:releaseId",
  RELEASE_DIFF: "/projects/:projectId/releases/:releaseId/diff",
  PROJECT_MEMBERS: "/projects/:projectId/members",
  SYNC_RECORD_LIST: "/projects/:projectId/sync-records",
  HEARTBEAT_LIST: "/projects/:projectId/heartbeats",
  AUDIT_LOG_LIST: "/projects/:projectId/audit-logs",
  // Platform admin routes
  ADMIN_DASHBOARD: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_CREATE_PROJECT: "/admin/projects/create",
} as const;
